version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  god_server:
    build: .
    restart: always
    ports:
      - 8000:80
    env_file: .env
    depends_on:
      - mongo
